import { createElement } from 'lwc';
import LwcQCHubHome from 'c/lwcQCHubHome';

describe('c-lwc-q-c-hub-home', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-lwc-q-c-hub-home', {
            is: LwcQCHubHome
        });
        document.body.appendChild(element);
    });
});