import { createElement } from 'lwc';
import LwcCohortStatistics from 'c/lwcCohortStatistics';

describe('c-lwc-cohort-statistics', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-lwc-cohort-statistics', {
            is: LwcCohortStatistics
        });
        document.body.appendChild(element);
    });
});