import { createElement } from 'lwc';
import LwcResultItem from 'c/lwcResultItem';

describe('c-lwc-result-item', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-lwc-result-item', {
            is: LwcResultItem
        });
        document.body.appendChild(element);
    });
});