import { createElement } from 'lwc';
import LwcMatchingQuestionType from 'c/lwcMatchingQuestionType';

describe('c-lwc-matching-question-type', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-lwc-matching-question-type', {
            is: LwcMatchingQuestionType
        });
        document.body.appendChild(element);
        expect(2).toBe(2);
    });
});