import { LightningElement } from 'lwc';

export default class QuestionTrackerTest extends LightningElement {
    list = [
        {
            Id: " 1",
            displayId: '1 \xa0',
            flagged: true,
            marked: false,
            answered: false,
            status: 'flagged',
        },
        {
            Id: "2 ",
            flagged: true,
            marked: false,
            answered: true,
            status: 'flagged',
        },
        {
            Id: "3 ",
            flagged: false,
            marked: true,
            answered: false,
            status: 'marked',
        },
        {
            Id: "4 ",
            flagged: false,
            marked: true,
            answered: true,
            status: 'marked',
        },
        {
            Id: "5 ",
            flagged: false,
            marked: false,
            answered: true,
            status: 'answered',
        },
        {
            Id: "6 ",
            flagged: false,
            marked: false,
            answered: true,
            status: 'answered',
        },
        {
            Id: "7 ",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "8 ",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "9 ",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "10",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "11",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "12",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "13",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "14",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "15",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "16",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "17",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "18",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "19",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "20",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "21",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "22",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "23",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "24",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "25",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "26",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },
        {
            Id: "27",
            flagged: false,
            marked: false,
            answered: false,
            status: 'unanswered',
        },

    ]
}