public class AuraGIFTParser {
    // *** VARIABLES *** //
    public List<ExamQuestion> allQuestions  { get; set; }
    // public List<String> missingWordQuestions  { get; set; }
    // public List<String> essayQuestions  { get; set; }
    // public List<String> numericalQuestions  { get; set; }
    // public List<String> matchingQuestions  { get; set; }
    // public List<String> multChoiceQuestions  { get; set; }
    // public List<String> multChoiceMQuestions  { get; set; }
    // public List<String> trueFalseQuestions  { get; set; }
    // public List<String> shortAnswerQuestions  { get; set; }
    
    // Aura
    @AuraEnabled
    public static void parseFile(List<ExamQuestion> questionList) {

    }
}
