import { createElement } from 'lwc';
import LwcTrueFalseQuestion from 'c/lwcTrueFalseQuestion';

describe('c-lwc-true-false-question', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-lwc-true-false-question', {
            is: LwcTrueFalseQuestion
        });
        document.body.appendChild(element);
        
        const v = element.shadowRoot.qu



        //debugger;
        //element.value = "T";
        //expect(element.LwcTrueFalseQuestion.answer()).toBe("T");


        //const tf = new LwcTrueFalseQuestion();
        //tf.value = "T";
        
    });
});