import { createElement } from 'lwc';
import D3ChartTest from 'c/d3ChartTest';

describe('c-d3-chart-test', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-d3-chart-test', {
            is: D3ChartTest
        });
        document.body.appendChild(element);
    });
});