import { createElement } from 'lwc';
import LwcHeroResultPage from 'c/lwcHeroResultPage';

describe('c-lwc-hero-result-page', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        const element = createElement('c-lwc-hero-result-page', {
            is: LwcHeroResultPage
        });
        document.body.appendChild(element);
    });
});